const INDOOR_MAP = {
  NOISE_SENSITIVITY_LOW: {
    NOISE_EXPOSURE_LOW: 42,
    NOISE_EXPOSURE_MODERATE: 47,
    NOISE_EXPOSURE_HIGH: 52,
    NOISE_EXPOSURE_VERY_HIGH: 57,
  },
  NOISE_SENSITIVITY_MODERATE: {
    NOISE_EXPOSURE_LOW: 47,
    NOISE_EXPOSURE_MODERATE: 52,
    NOISE_EXPOSURE_HIGH: 57,
    NOISE_EXPOSURE_VERY_HIGH: 62,
  },
  NOISE_SENSITIVITY_HIGH: {
    NOISE_EXPOSURE_LOW: 52,
    NOISE_EXPOSURE_MODERATE: 57,
    NOISE_EXPOSURE_HIGH: 62,
    NOISE_EXPOSURE_VERY_HIGH: 67,
  },
};

const OUTDOOR_MAP = {
  NOISE_SENSITIVITY_LOW: {
    NOISE_EXPOSURE_LOW: 42,
    NOISE_EXPOSURE_MODERATE: 47,
    NOISE_EXPOSURE_HIGH: 52,
    NOISE_EXPOSURE_VERY_HIGH: 57,
  },
  NOISE_SENSITIVITY_MODERATE: {
    NOISE_EXPOSURE_LOW: 47,
    NOISE_EXPOSURE_MODERATE: 52,
    NOISE_EXPOSURE_HIGH: 57,
    NOISE_EXPOSURE_VERY_HIGH: 62,
  },
  NOISE_SENSITIVITY_HIGH: {
    NOISE_EXPOSURE_LOW: 52,
    NOISE_EXPOSURE_MODERATE: 57,
    NOISE_EXPOSURE_HIGH: 62,
    NOISE_EXPOSURE_VERY_HIGH: 67,
  },
};
